### ISSUE TITLE
List component

### ISSUE THREAD

**Issue by jurajhrib** [Byteclaw/visage#15]
- [x] - Item
- [x] - Container
- [x] - Divider

?? - heading

**Comment by michalkvasnicak** [comment]
I think we need these components: `ListItem, ListHeading, ListDivider`

collapsible sublists should be made from composition of `Accordion` and another nested `List`. Because of that `ListItems` should be able to have som sort of a toggle or be a toggle itself. But it's rather a problem of composition, we don't need to have a special component for every kind of interaction.
