### ISSUE TITLE
[Menu] - should use onClose from CloseListenerManager

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#330]
Maybe we should get rid of `disableEvents` prop ?

**Comment by jurajhrib** [comment]
@michalkvasnicak 

This is what needs to happen:

- disableEvents gets removed
- disableAutoFocusItem gets added
- when disabelAutoFocusItem=true, we have to register a global listener for ArrowUp and ArrowDown, which will on first hit focus first/last item and remove the global listeners. 

This is a consistent way of handling the arrows, no matter what user decides to do with the first focus event. 

There is still an edge case - when user decides to do all focusing on his own, then we should not really focus the first/last item from global scope.

Maybe it can be solved by introducing slightly different approach - have a global listener, which is triggered (or registered) only while no item from the list is focused. This could be done by a simple ref variable. This could cause problem in another edge case - if we render more Menus (like nested Menus/Dropdowns), because then, you would spawn multiple listeners. But is this even a use-case?

**Comment by michalkvasnicak** [comment]
I'm not sure I understand global listener. Do you mean `document.addEventListener`? How it works?

1. I'll focus an AutocompleteInput
2. I'll press ArrowUp/ArrowDown and the dropdown will open?
3. After opening the dropdown, global listener is removed?

And if I use `disableAutoFocusItem={false}` then the event handling is registered on a component?

Case for multiple menus could be dropdown menu with nested menus for example material ui has a support for that.
